### PR TITLE
Translations updated (english placeholder)

### LINKED ISSUE #621: SettingsAccountAgeCheckbox error not localized
SettingsAccountAgeCheckbox  When not checked the app throws an error for folsk previously logged in but who did not check this box.

### PR DESCRIPTION
**Pull request by gioneill**
fixes #621

### CODE REVIEW

**Comment by gioneill** [comment]
I realize now the binary files can't be diff'ed, but I essentially found all the key/values present in English that were not present in the other languages, and copied them in. This prevents Keys from displaying for all those strings in the other languages.

**Comment by aferditamuriqi** [comment]
@gioneill this should be going through transifex, and we shouldn't have english text in other languages. in general if the key is not present in other languages, the OS would default back to the default language, which I believe is set to english,

**Comment by gioneill** [comment]
The OS is not defaulting to English though.. we either need to keep English versions in there temporarily, OR go back to the source of all those strings (30+) and change the keys to the english values.

simulator screen shot may 23 2017 11 08 21 am

**Comment by aferditamuriqi** [comment]
there is definitely something not right there, but i would not prefer having english placeholders. let me take a look and i'll get back to you.

**Comment by aferditamuriqi** [comment]
as suspected we are not using base internationalization. i'll send you some notes in slack.

**Pull request closed without merging**
