### PR TITLE
Axis download content

### PR DESCRIPTION
**Pull request by singhraman4282**
**What's this do?**
Allows download of axis drm content

**Why are we doing this? (w/ JIRA link if applicable)**
https://jira.nypl.org/browse/SIMPLY-3599

**How should this be tested? / Do these changes have associated tests?**
Can not be QA tested as of now.

**Dependencies for merging? Releasing to production?**
Needs to remove the commit b1dc95e before merging into production

**Does this include changes that require a new SimplyE build for QA?**
N/A

**Has the application documentation been updated for these changes?**
N/A

**Did someone actually run this code to verify it works?**
Raman Singh tested it

### CODE REVIEW

**Comment by ettore** [comment]
@singhraman4282 Is it necessary to check in these temporary hacks? Are you checking them in to be able to provide a build for QA?  In that commit there's also Xcode project references which obviously have no TODOs -- I'm just wondering how we seep track of all this.

I suppose TODOs are great for marking incomplete works, but for tracking hacks are less good... I'm trying to think of a better way to track them. Open to ideas also from @ErnestFan.

2nd thing, make sure the CI checks are passing, currently one is failing.

**Comment by singhraman4282** [comment]
@ettore The hack is currently required for two reasons
1. User is unable to use beta libraries ([SIMPLY-3671](https://jira.nypl.org/browse/SIMPLY-3671))
2. All the books in qa libraries have two links (one for adept, one for axix) and the app defaults to adept link for downloading.

This hack can be removed after SIMPLY-3671 is fixed and the axis link is made the preferred link.

Regarding the test failing, It's failing because of the changes made to sign in flow to accommodate using beta libraries without the fix for SIMPLY-3671.

This pr can wait until a fix for SIMPLY-3671 has been merged in. But then again, in order to make it testable for QA, we'll have to include a change that forces the app to prioritize axis links over adept links. Before merging it on to develop branch, that change will have to be removed.

I'm open to all suggestions/ideas. If you and @ErnestFan can think of a more suitable approach that would be highly appreciated.

**Comment by ErnestFan** [comment]
The hack seems reasonable but maybe we can use `FIXME` instead of `TODO` to keep track of the hacks.

Also, list out the files that should be removed from the codebase once the hack is no longer needed in one of the `FIXME/TODO`, eg. `44628feed.xml` etc.

**Comment by ettore** [comment]
> 1. User is unable to use beta libraries ([SIMPLY-3671](https://jira.nypl.org/browse/SIMPLY-3671))
> 2. All the books in qa libraries have two links (one for adept, one for axix) and the app defaults to adept link for downloading.
> 
> This hack can be removed after SIMPLY-3671 is fixed and the axis link is made the preferred link.
> 
> Regarding the test failing, It's failing because of the changes made to sign in flow to accommodate using beta libraries without the fix for SIMPLY-3671.

Sounds good. Please make a note in the ticket so that we know what to expect.

> This pr can wait until a fix for SIMPLY-3671 has been merged in. But then again, in order to make it testable for QA, we'll have to include a change that forces the app to prioritize axis links over adept links. Before merging it on to develop branch, that change will have to be removed.

But before we ship, don't we want Open eBooks to _only_ use Axis DRM instead of Adobe? As far as I understood, Adobe shouldn't even be compiled into the app anymore once this feature is completed.

**Comment by singhraman4282** [comment]
@ettore and @ErnestFan thank you so much for your feedback. Since we do not want to add more hacks and FIXMEs to the codebase, PR for https://jira.nypl.org/browse/SIMPLY-3671 has been created. Once that gets merged in along with a PR for https://jira.nypl.org/browse/SIMPLY-3687, I'll remove the hack and resubmit the PR.

**Pull request closed without merging**
