### PR TITLE
Add alameda to library list

### PR DESCRIPTION
**Pull request by datalogics-tarar**
Added Alameda county library in California to the list of libraries in the SimplyE app along with their logos.

### CODE REVIEW

**Comment by datalogics-bhaugen** [comment]
@aferditamuriqi, please coordinate with us before merging this branch so that Alameda does not accidentally get released before we are completely ready to do so.

(Similar to the PR on Android, I just like having an explicit statement on each of these so they don't get accidentally merged 😄)

**Comment by aferditamuriqi** [comment]
Absolutely. It's noted .

**Comment by gioneill** [comment]
I've pushed a commit onto this PR that does a few things:
- Consolidates the work from the two other datalogics PR's
- Resolves a merge conflict between two of the PR's
- Allows libraries to set their Username/PIN requirements in the JSON file

This one PR should now be the complete update for bringing Alameda County into the library list:
- Adds the library, all associated image assets
- Allows unlimited characters for passcode and alphanumeric keyboard

**Comment by winniequinn** [comment]
@gioneill I am okay with this but I'd like you to double-check before merging! If you are okay with it too, feel free to go ahead and merge.

**Comment by gioneill** [comment]
Just holding here until Datalogics lets us know they're ready to bring the library into a release.

**Comment by gioneill** [comment]
It looks like these new commits are for Montgomery and not Alameda County.

**Comment by gioneill** [comment]
Develop has been deprecated. Commits from this PR are incorporated into new branch `datalogics_new_libraries` which has been branched from Master.

**Pull request closed without merging**
