### PR TITLE
SIMPLY-3356 NYU Book status wording

### PR DESCRIPTION
**Pull request by vladimirfedorov**
**What's this do?**
- change book details "This open-access book is available to keep" to "This book is available to borrow." for cases when the book is available and has no specified number of total or available to borrow items.
- removes `NYPLBookButtonsStateCanKeep` case from `NYPLBookButtonsState` 

**Why are we doing this? (w/ JIRA link if applicable)**
https://jira.nypl.org/browse/SIMPLY-3356
Currently NYU book details display the misleading status "This open-access book is available to keep". This status appears when OPDS entries for these books don't have any specified amount available to borrow and isn't connected with "open-access" link relation.

**How should this be tested? / Do these changes have associated tests?**
In "New York University Libraries" tap any book, e.g., "A Doll's House". Book status should read "This book is available to borrow.".

**Dependencies for merging? Releasing to production?**
No

**Has the application documentation been updated for these changes?**
N/A

**Did someone actually run this code to verify it works?**
@vladimirfedorov

### CODE REVIEW

**Review by leonardr — COMMENTED** [review]
This branch removes the "yours to keep" language altogether, rather than fixing it to only apply to books that are actually open-access. This is my preferred solution but I don't want to merge this code until we've actually agreed to go in that direction.

We also need to investigate whether this issue applies on Android, and make the messaging consistent across platforms. Removing the language here means also removing it from Android, even though I'm guessing Android displays the message only for actual open-access books.

**Comment by vbessonov** [comment]
@vladimirfedorov, could you keep `This open-access book is available to keep` for open-access acquisition links to not change the current behaviour?

**Review by ettore — APPROVED** [review]
after reading the ticket, these changes make sense to me code-wise, but my approval is conditional to @leonardr's for timing about when we should merge this.

**Comment by vladimirfedorov** [comment]
> @vladimirfedorov, could you keep `This open-access book is available to keep` for open-access acquisition links to not change the current behaviour?

Currently the app doesn't have that feature, we can't keep this line for open-access acquisitions but instead we can add this feature the way it is done on Android. If Android displays this text correctly, we can add the same logics to iOS version of the app.

**Review by leonardr — APPROVED** [review]
Risa has approved removing this message altogether until we come up with a better solution.

**Pull request merged**
