### PR TITLE
Integrate PDF Reader with No Data Saving/Synching

### PR DESCRIPTION
**Pull request by vuinguyen**
This PR addresses JIRA issue: https://jira.nypl.org/browse/SIMPLY-175
by enabling a PDF renderer to open and display PDF books within SimplyE. 

Data (ie bookmarks and annotations) is not being saved locally in between app restarts, nor is data being saved or synced to a server.

### CODE REVIEW

**Comment by MalcolmMcFly** [comment]
@kyles-ep has it been discussed what we are doing with this?

**Comment by kyles-ep** [comment]
@MalcolmMcFly I don't have the necessary historic knowledge to comment on this PR. It looks like this is for adding a PDF viewer, but we already have one in the app.

**Comment by MalcolmMcFly** [comment]
@kyles-ep so I think I am going to close this PR if that is ok with you.

**Comment by swandog30** [comment]
This was work that Minitex did last year integrating a commercial PDF renderer.  Go ahead and close it.

**Pull request closed without merging**
